# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import replication_pb2 as protos_dot_replication__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/replication.ReplicationService/Read',
                request_serializer=protos_dot_replication__pb2.ReadRequest.SerializeToString,
                response_deserializer=protos_dot_replication__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/replication.ReplicationService/Write',
                request_serializer=protos_dot_replication__pb2.WriteRequest.SerializeToString,
                response_deserializer=protos_dot_replication__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.PropagateOtherLayers = channel.unary_unary(
                '/replication.ReplicationService/PropagateOtherLayers',
                request_serializer=protos_dot_replication__pb2.PropagateOtherLayersRequest.SerializeToString,
                response_deserializer=protos_dot_replication__pb2.PropagateOtherLayersResponse.FromString,
                _registered_method=True)
        self.PropagateCoreNodes = channel.unary_unary(
                '/replication.ReplicationService/PropagateCoreNodes',
                request_serializer=protos_dot_replication__pb2.PropagateCoreNodesRequest.SerializeToString,
                response_deserializer=protos_dot_replication__pb2.PropagateCoreNodesResponse.FromString,
                _registered_method=True)


class ReplicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateOtherLayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateCoreNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=protos_dot_replication__pb2.ReadRequest.FromString,
                    response_serializer=protos_dot_replication__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=protos_dot_replication__pb2.WriteRequest.FromString,
                    response_serializer=protos_dot_replication__pb2.WriteResponse.SerializeToString,
            ),
            'PropagateOtherLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateOtherLayers,
                    request_deserializer=protos_dot_replication__pb2.PropagateOtherLayersRequest.FromString,
                    response_serializer=protos_dot_replication__pb2.PropagateOtherLayersResponse.SerializeToString,
            ),
            'PropagateCoreNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateCoreNodes,
                    request_deserializer=protos_dot_replication__pb2.PropagateCoreNodesRequest.FromString,
                    response_serializer=protos_dot_replication__pb2.PropagateCoreNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.ReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/Read',
            protos_dot_replication__pb2.ReadRequest.SerializeToString,
            protos_dot_replication__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/Write',
            protos_dot_replication__pb2.WriteRequest.SerializeToString,
            protos_dot_replication__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateOtherLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/PropagateOtherLayers',
            protos_dot_replication__pb2.PropagateOtherLayersRequest.SerializeToString,
            protos_dot_replication__pb2.PropagateOtherLayersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateCoreNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/PropagateCoreNodes',
            protos_dot_replication__pb2.PropagateCoreNodesRequest.SerializeToString,
            protos_dot_replication__pb2.PropagateCoreNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
