# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/replication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/replication.proto\x12\x0breplication\"&\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\"<\n\x0cReadResponse\x12\r\n\x05valor\x18\x01 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\x12\x10\n\x08missatge\x18\x03 \x01(\t\"6\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\t\".\n\rWriteResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x12\x10\n\x08missatge\x18\x02 \x01(\t\"\x9c\x01\n\x1bPropagateOtherLayersRequest\x12@\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x32.replication.PropagateOtherLayersRequest.DataEntry\x12\x0e\n\x06versio\x18\x02 \x01(\x05\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"+\n\x1cPropagateOtherLayersResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"\xa9\x01\n\x19PropagateCoreNodesRequest\x12>\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x30.replication.PropagateCoreNodesRequest.DataEntry\x12\x0e\n\x06versio\x18\x02 \x01(\x05\x12\x0f\n\x07id_send\x18\x03 \x01(\t\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\")\n\x1aPropagateCoreNodesResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32\xe5\x02\n\x12ReplicationService\x12;\n\x04Read\x12\x18.replication.ReadRequest\x1a\x19.replication.ReadResponse\x12>\n\x05Write\x12\x19.replication.WriteRequest\x1a\x1a.replication.WriteResponse\x12k\n\x14PropagateOtherLayers\x12(.replication.PropagateOtherLayersRequest\x1a).replication.PropagateOtherLayersResponse\x12\x65\n\x12PropagateCoreNodes\x12&.replication.PropagateCoreNodesRequest\x1a\'.replication.PropagateCoreNodesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPAGATEOTHERLAYERSREQUEST_DATAENTRY']._loaded_options = None
  _globals['_PROPAGATEOTHERLAYERSREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_PROPAGATECORENODESREQUEST_DATAENTRY']._loaded_options = None
  _globals['_PROPAGATECORENODESREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_READREQUEST']._serialized_start=41
  _globals['_READREQUEST']._serialized_end=79
  _globals['_READRESPONSE']._serialized_start=81
  _globals['_READRESPONSE']._serialized_end=141
  _globals['_WRITEREQUEST']._serialized_start=143
  _globals['_WRITEREQUEST']._serialized_end=197
  _globals['_WRITERESPONSE']._serialized_start=199
  _globals['_WRITERESPONSE']._serialized_end=245
  _globals['_PROPAGATEOTHERLAYERSREQUEST']._serialized_start=248
  _globals['_PROPAGATEOTHERLAYERSREQUEST']._serialized_end=404
  _globals['_PROPAGATEOTHERLAYERSREQUEST_DATAENTRY']._serialized_start=361
  _globals['_PROPAGATEOTHERLAYERSREQUEST_DATAENTRY']._serialized_end=404
  _globals['_PROPAGATEOTHERLAYERSRESPONSE']._serialized_start=406
  _globals['_PROPAGATEOTHERLAYERSRESPONSE']._serialized_end=449
  _globals['_PROPAGATECORENODESREQUEST']._serialized_start=452
  _globals['_PROPAGATECORENODESREQUEST']._serialized_end=621
  _globals['_PROPAGATECORENODESREQUEST_DATAENTRY']._serialized_start=361
  _globals['_PROPAGATECORENODESREQUEST_DATAENTRY']._serialized_end=404
  _globals['_PROPAGATECORENODESRESPONSE']._serialized_start=623
  _globals['_PROPAGATECORENODESRESPONSE']._serialized_end=664
  _globals['_REPLICATIONSERVICE']._serialized_start=667
  _globals['_REPLICATIONSERVICE']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
